### ISSUE TITLE
Custom models don't work

### ISSUE THREAD

**Issue by bufke** [ulule/django-badgify#4]
I'm having a few issues. The first is simple. in README.md it says

```
from badgify.models import base

class Badge(base.Badge):
```

However the full path is badgify.models.base.badge.Badge. it should probably be something like 

```
from badgify.models.base.badge import Badge as BaseBadge

class Badge(BaseBadge):
```

Even so I get a mysterious stack trace when trying to create the migration. Do you have any fuller example of a custom model?

```
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 443, in execute
    self.check()
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 481, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/site-packages/django/core/checks/model_checks.py", line 28, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 1183, in check
    errors.extend(cls._check_long_column_names())
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 1624, in _check_long_column_names
    for m2m in f.rel.through._meta.local_fields:
AttributeError: 'str' object has no attribute '_meta'
```

If I try to define both badge and award I get instead

```
my_badges.Award.badge: (fields.E300) Field defines a relation with model 'badgify.Badge', which is either not installed, or is abstract.
my_badges.Award: (fields.E336) The model is used as an intermediate model by 'my_badges.Badge.users', but it does not have a foreign key to 'Badge' or 'User'.
```

I can't redefine the relations because Django won't allow that.

**Comment by bufke** [comment]
I finally got it to somewhat work by ensuring the following:

1. Keep the class name Badge/Award. Don't change them.
2. Do not change Meta.app_label
3. Always import models from badgify, never from my custom model.

However migrations don't work - which initially made me think this method wasn't working. It's because the models work as though they are part of the app badgify still. If we run makemigrations badgify it would add the migration file to the badgify package and not the app I create to keep these custom models. I can work around this by running raw sql instead of running the migration but that is clearly a bad hack.

Any ideas? Am I approaching this wrong?

**Comment by gillesfabio** [comment]
Hi @bufke,

Thanks for your feedback!

Custom model classes work like a charme on our code base.

Did you add `abstract = False` to your custom models?

```python
from badgify.models.base.badge import Badge

class MyCustomBadge(Badge):
    class Meta(Badge.Meta):
        abstract = False
```

Did you setup settings? 

```
# yourapp.settings

BADGIFY_BADGE_MODEL = 'yourapp.models.Badge'
BADGIFY_AWARD_MODEL = 'yourapp.models.Award'
```

This feature needs a better documentation and an practical example. I will work on this.

Is it possible that you setup an quick and dirty example project to reproduce your error (and push it somewhere on GitHub)?

Thanks.

**Comment by Q-bart** [comment]
Hello! Have the same problem with custom model Badge. 

My code -  https://gist.github.com/Q-bart/adb3e82a779e81f76714

and when I run `manage.py makemigrations main`,  I get this error:

``Traceback (most recent call last):
  File "D:\virtenvs\codeguida_for_time\lib\site-packages\badgify\utils.py", line 77, in load_class
    clazz = getattr(mod, class_name)
AttributeError: 'module' object has no attribute 'GuidaBadge'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\virtenvs\codeguida_for_time\codeguida\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\virtenvs\codeguida_for_time\lib\site-packages\django\core\management\__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "D:\virtenvs\codeguida_for_time\lib\site-packages\django\core\management\__init__.py", line 354, in execute
    django.setup()
  File "D:\virtenvs\codeguida_for_time\lib\site-packages\django\__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\virtenvs\codeguida_for_time\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "D:\virtenvs\codeguida_for_time\lib\site-packages\django\apps\config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "D:\virtenvs\codeguida_for_time\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "D:\virtenvs\codeguida_for_time\codeguida\main\models.py", line 10, in <module>
    from badgify.models.base.badge import Badge as BaseBadge
  File "D:\virtenvs\codeguida_for_time\lib\site-packages\badgify\models\__init__.py", line 8, in <module>
    Badge = load_class(settings.BADGE_MODEL)
  File "D:\virtenvs\codeguida_for_time\lib\site-packages\badgify\utils.py", line 86, in load_class
    raise exceptions.ImproperlyConfigured(txt)
django.core.exceptions.ImproperlyConfigured: Backend module "main.models" does not define a "GuidaBadge" class.``

Can you prompt me how to fix it?


P.S. Also: 
> Custom model classes work like a charme on our code base.

Can you share your code, maybe I miss something?

**Comment by bufke** [comment]
@Q-bart I never saw that particular error. I'm afraid I didn't follow up on this issue due to lack of time. I was able to get it working my running migrations with raw sql. I can't share my entire code base but you can check out my models. My issue was that makemigrations would add the migrations in the badgify app instead of the app I made (which of course is not going to work).

myapp/models.py
```
from django.db import models
from utils.model_mixins import OrderMixin
from badgify.models.base.badge import Badge as BaseBadge
from badgify.models.base.award import Award as BaseAward


class Badge(OrderMixin, BaseBadge):
    criteria_description = models.TextField(blank=True)
    image_inactive = models.ImageField(blank=True)

    class Meta(BaseBadge.Meta):
        abstract = False
        ordering = ('position',)


class Award(BaseAward):
    class Meta(BaseAward.Meta):
        abstract = False
```

settings.py
```
BADGIFY_BADGE_MODEL = 'myapp.models.Badge'
BADGIFY_AWARD_MODEL = 'myapp.models.Award'
```

**Comment by Q-bart** [comment]
@bufke What is the OrderMixin?

**Comment by Q-bart** [comment]
It seems that error occures here https://github.com/ulule/django-badgify/blob/master/badgify/utils.py#L72

I try to use load_class function from `manage.py shell` , by passing the same argument `class_path`
And it runs perfectly. 

But when I try to run `makemigrations ` with `BADGIFY_BADGE_MODEL` in my settings - it raise me this error https://github.com/ulule/django-badgify/blob/master/badgify/utils.py#L79

I have tried to print `class_path` argument in fuction - everytime it was the same..

I don`t know what to do. Any Ideas?
