### ISSUE TITLE
Installation Error: utils.py line 56 (Python3 incompatability?)

### ISSUE THREAD

**Issue by tylerecouture** [ulule/django-badgify#5]
When I try to run ./manage.py migrate:
`@sparagus ~/Developer/hackerspace_online/src $ ./manage.py makemigrations
/home/couture/Developer/hackerspace_online/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  return f(*args, **kwds)

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/couture/Developer/hackerspace_online/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/couture/Developer/hackerspace_online/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/couture/Developer/hackerspace_online/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/couture/Developer/hackerspace_online/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/couture/Developer/hackerspace_online/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/couture/Developer/hackerspace_online/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/couture/Developer/hackerspace_online/lib/python3.4/site-packages/badgify/models/__init__.py", line 5, in <module>
    from ..utils import load_class
  File "/home/couture/Developer/hackerspace_online/lib/python3.4/site-packages/badgify/utils.py", line 56
    except ImportError, e:
(hackerspace_online)couture@sparagus ~/Developer/hackerspace_online/src $ ./manage.py makemigrations
/home/couture/Developer/hackerspace_online/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  return f(*args, **kwds)

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/couture/Developer/hackerspace_online/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/couture/Developer/hackerspace_online/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/couture/Developer/hackerspace_online/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/couture/Developer/hackerspace_online/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/couture/Developer/hackerspace_online/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/couture/Developer/hackerspace_online/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/couture/Developer/hackerspace_online/lib/python3.4/site-packages/badgify/models/__init__.py", line 5, in <module>
    from ..utils import load_class
  File "/home/couture/Developer/hackerspace_online/lib/python3.4/site-packages/badgify/utils.py", line 56
    except ImportError, e:`
                      ^
SyntaxError: invalid syntax

**Comment by tylerecouture** [comment]
oh, it looks like pip install gave me badgify v1.5, yet I'm running python 3.4

**Comment by mjpieters** [comment]
This appears addressed already by [this commit from June 2015](https://github.com/ulule/django-badgify/commit/b726bf8e712f9ac79bedd60b3c1b35a6fffd8c07); but the last release (0.1.5) was cut in April that year. Looks like you'll have to use the GitHub master branch instead.

**Comment by thoas** [comment]
released to pypi to 0.1.6
